package ch.mtrail.demo.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Zugfahrt generated by hbm2java
 */
public class Zugfahrt {

	private Integer trainId;
	private String evu;
	private int zugNr;
	private int laufNr;
	private Date betriebsTag;
	private int versionNumber;
	private boolean isFakZugfahrt;
	private boolean isNationalTrain;
	private boolean isPassengerTrain;
	private Set<ZugfahrtSollpunkte> zugfahrtSollpunkte = new HashSet<>();

	public Zugfahrt() {
	}

	public Zugfahrt(String evu, int zugNr, int laufNr, Date betriebsTag, int versionNumber, boolean isFakZugfahrt,
			boolean isNationalTrain, boolean isPassengerTrain) {
		this.evu = evu;
		this.zugNr = zugNr;
		this.laufNr = laufNr;
		this.betriebsTag = betriebsTag;
		this.versionNumber = versionNumber;
		this.isFakZugfahrt = isFakZugfahrt;
		this.isNationalTrain = isNationalTrain;
		this.isPassengerTrain = isPassengerTrain;
	}

	public Zugfahrt(String evu, int zugNr, int laufNr, Date betriebsTag, int versionNumber, boolean isFakZugfahrt,
			boolean isNationalTrain, boolean isPassengerTrain, Set<ZugfahrtSollpunkte> zugfahrtSollpunkte) {
		this.evu = evu;
		this.zugNr = zugNr;
		this.laufNr = laufNr;
		this.betriebsTag = betriebsTag;
		this.versionNumber = versionNumber;
		this.isFakZugfahrt = isFakZugfahrt;
		this.isNationalTrain = isNationalTrain;
		this.isPassengerTrain = isPassengerTrain;
		this.zugfahrtSollpunkte = zugfahrtSollpunkte;
	}

	public Integer getTrainId() {
		return this.trainId;
	}

	public void setTrainId(Integer trainId) {
		this.trainId = trainId;
	}

	public String getEvu() {
		return this.evu;
	}

	public void setEvu(String evu) {
		this.evu = evu;
	}

	public int getZugNr() {
		return this.zugNr;
	}

	public void setZugNr(int zugNr) {
		this.zugNr = zugNr;
	}

	public int getLaufNr() {
		return this.laufNr;
	}

	public void setLaufNr(int laufNr) {
		this.laufNr = laufNr;
	}

	public Date getBetriebsTag() {
		return this.betriebsTag;
	}

	public void setBetriebsTag(Date betriebsTag) {
		this.betriebsTag = betriebsTag;
	}

	public int getVersionNumber() {
		return this.versionNumber;
	}

	public void setVersionNumber(int versionNumber) {
		this.versionNumber = versionNumber;
	}

	public boolean isIsFakZugfahrt() {
		return this.isFakZugfahrt;
	}

	public void setIsFakZugfahrt(boolean isFakZugfahrt) {
		this.isFakZugfahrt = isFakZugfahrt;
	}

	public boolean isIsNationalTrain() {
		return this.isNationalTrain;
	}

	public void setIsNationalTrain(boolean isNationalTrain) {
		this.isNationalTrain = isNationalTrain;
	}

	public boolean isIsPassengerTrain() {
		return this.isPassengerTrain;
	}

	public void setIsPassengerTrain(boolean isPassengerTrain) {
		this.isPassengerTrain = isPassengerTrain;
	}
	
	public Set<ZugfahrtSollpunkte> getZugfahrtSollpunkte() {
		return zugfahrtSollpunkte;
	}
	
	public void setZugfahrtSollpunkte(Set<ZugfahrtSollpunkte> zugfahrtSollpunkte) {
		this.zugfahrtSollpunkte = zugfahrtSollpunkte;
	}
	
	public String getZugId() {
		return getEvu() + "-" + getZugNr() + "-" + getLaufNr();
	}
	
	public String toString() {
		return getZugId() + " " + getBetriebsTag();
	}
}
